### ISSUE TITLE
Deprecation Warnings Created by Changes to mbed-os

### ISSUE THREAD

**Issue by mattbrown015** [ARMmbed/mbed-semtech-lora-rf-drivers#30]
### Description
[Add ThisThread namespace and deprecate static Thread methods #7872](https://github.com/ARMmbed/mbed-os/pull/7872) means that there are 8 warnings from `SX1276_LoRaRadio.cpp`.

> Compile [ 96.7%]: SX1276_LoRaRadio.cpp
> [Warning] SX1276_LoRaRadio.cpp@1150,64: 'static osEvent rtos::Thread::signal_wait(int32_t, uint32_t)' is deprecated: Static methods only affecting current thread cause confusion. Replaced by ThisThread::flags_wait_all, ThisThread::flags_wait_all_for, ThisThread::flags_wait_any and ThisThread:wait_any_for. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1759,34: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1768,35: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1777,35: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1786,35: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1795,35: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1804,35: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]
> [Warning] SX1276_LoRaRadio.cpp@1816,37: 'int32_t rtos::Thread::signal_set(int32_t)' is deprecated: Other signal_xxx methods have been deprecated in favour of ThisThread::flags functions. To match this naming scheme, derived from CMSIS-RTOS2, Thread::flags_set is now provided. [since mbed-os-5.10] [-Wdeprecated-declarations]

Not the end of the world I know, but pretty unsightly.

The warnings are easy to get rid of but then any users would have to update to mbed-os V5.10.0 if they update the drivers.

Is this a reasonable requirement?

Can we fix the warnings and tidy-up my build? :-)

### Issue request type
[ ] Question  
[ ] Enhancement  
[X] Bug

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1319

**Comment by mattbrown015** [comment]
See #32
