### ISSUE TITLE
SX1278 support?

### ISSUE THREAD

**Issue by ccchang12** [ARMmbed/mbed-semtech-lora-rf-drivers#46]
Does this driver support SX1278 module? If not, is there any driver to support SX1278 module?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2149

**Comment by AnttiKauppila** [comment]
No it does not. There might be some drivers available, but we haven't tested those.

**Comment by ccchang12** [comment]
We have some mbed-os users in China want to use LoRaWAN. Do you have a plan to support SX1278?
