### ISSUE TITLE
Add Semtech drivers configuration as mbed-os component ?

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-semtech-lora-rf-drivers#51]
Hi

Just wondering why these files are not part of mbed-os ?
As COMPONENT for ex ?

Thx

@0xc0170 
@MarceloSalazar

**Comment by 0xc0170** [comment]
I don't recall.

cc @AnttiKauppila

**Comment by AnttiKauppila** [comment]
It was a decision made while bringing LoRaWAN stack into Mbed OS 5.7. The reason given was to keep Mbed OS as light-weight as possible (if I remember correctly).

**Comment by jeromecoutant** [comment]
Goal would be to enable LORA in default configuration for DISCO_L072CZ_LRWAN1

and also for coming STM32WL chips

**Comment by AnttiKauppila** [comment]
That is a good reason to bring the drivers into Mbed Os. I need to fix one licence header for SX1262 driver, but after that it needs only a PR to be made for Mbed Os.

**Comment by jeromecoutant** [comment]
@LMESTM

**Comment by AnttiKauppila** [comment]
Copyright should be fine now

**Comment by jeromecoutant** [comment]
@AnttiKauppila any updates ?

**Comment by kivaisan** [comment]
PR to include Lora drivers in mbed-os: https://github.com/ARMmbed/mbed-os/pull/12741

**Comment by kivaisan** [comment]
PR got merged, so closing this issue. In order to use driver corresponding component must be enabled in mbed_app.json. E.g.:
`"target.components_add": ["SX126X"],`
