### ISSUE TITLE
SPI_FREQUENCY configuration points to wrong define

### ISSUE THREAD

**Issue by MortenGuldager** [ARMmbed/mbed-semtech-lora-rf-drivers#52]
In `SX1272/SX1272_LoRaRadio.cpp` line 35 and 36 the macro `MBED_SX1272_LORA_RADIO_SPI_FREQUENCY` is referenced.

But in `SX1272/mbed_lib.json` it seems to be named `sx1272-lora-driver` . `spi-frequency` which is exapanded to `MBED_CONF_SX1272_LORA_DRIVER_SPI_FREQUENCY`

I guess they were supposed to have the same name. Otherwise I would like to hear how to change SPI freq.

**Comment by kivaisan** [comment]
Fixed with 68beebfd11f629ba34c4656d2e1d3183a4539301

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2455
